S = (headline|emptyline)*

<s> = <#"\s+">
whitespace = #'\s'
endofline = #'$'
newline = '\n'
<eol> = <(newline|endofline)>
<word> = #'[^\n\s]+'

emptyline = whitespace* <(newline|endofline)>

headline = stars [s priority] [s comment-flag] s title [s tags] eol
stars = #'\*+'
priority = <"[#"> #"[A-Z]" <"]">
comment-flag = <"COMMENT">
title = !tags word {<whitespace+> !tags word}
tags = <':'> { tag <':'> }
<tag> = #'[a-zA-Z0-9_@#%]+'


(* UNTESTED

affiliated_keywords = "#+" (key | attr_backend) ": " value
optional = "[" value "]"
value =
key = "HEADER" | "NAME" | "PLOT" | (("RESULTS" | "CAPTION") [ optional ])
attr_backend = "ATTR_" backend
backend = #"[a-zA-Z0-9-_]+"

greater_block = '#+BEGIN_' name [whitespace parameters] newline contents '#+END_' name
name = #'[^\s]+'
parameters = #'[^\n]+'

dynamic_block = '#+BEGIN:' whitespace name [whitespace parameters] contents '#+END:'

*)
